app = "ktv-multilayer-api"
primary_region = "sin"

[build]

[env]
  APP_ENV = "production"
  PORT = "8000"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "30s"
  grace_period = "10s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "15s"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = "ktv_data"
  destination = "/app/data"

# Tambahan untuk deployment optimization
[processes]
  app = "python app.py"

[deploy]
  strategy = "rolling"